# ./docker-compose.yml

version: '3'

services:
  web:
    image: php/php_pdo:1.0
    container_name: php_web
    volumes:
      - "./performia_php/:/var/www/html/"
      - "./config/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "8080:80"
    stdin_open: true
    tty: true